# Regulation Retriever Agent Configuration

# Model Configuration
embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  max_length: 384
  device: "cpu"  # or "cuda" if available

# Chunking Parameters
chunking:
  min_chars: 600
  max_chars: 900
  overlap_ratio: 0.15
  preserve_sections: true

# Vector Index Configuration
index:
  similarity_metric: "cosine"
  index_type: "faiss"
  dimension: 384  # all-MiniLM-L6-v2 embedding size
  cache_size: 1000

# RAG Configuration
rag:
  vectorstore:
    type: "faiss"
    index_path: "index/faiss/index.faiss"
    id_map_path: "index/faiss/id_map.jsonl"
    metric: "ip"
    normalize: true
  retriever:
    top_k: 5
  agents:
    tiktok_feature_generator:
      compliance_validation: true
      regulatory_context_top_k: 3
    compliance_analyzer:
      analysis_top_k: 5
      jurisdiction_filtering: true
    compliance_reporter:
      reporting_top_k: 3
      evidence_logging: true

# Evidence Logging Configuration
evidence:
  enabled: true
  sink:
    path: "data/evidence"
    rotation: "by_day"  # by_day or by_size_mb
    size_mb: 100
  retention_days: 90
  redact:
    enabled: true
    patterns:
      - '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'  # Email
      - '\b\d{3}[-.]?\d{3}[-.]?\d{4}\b'  # Phone
      - '\b\d{4}[- ]?\d{4}[- ]?\d{4}[- ]?\d{4}\b'  # Credit card
      - '\b[A-Z]{2}\d{2}[A-Z0-9]{10,30}\b'  # IBAN
      - '\b\d{3}-\d{2}-\d{4}\b'  # SSN
      - '\b[A-Za-z0-9]{20,}\b'  # Long tokens/keys
  flush_interval: 1
  sync: false

# Retrieval Configuration
retrieval:
  bm25_weight: 0.3
  dense_weight: 0.7
  max_results: 20
  rerank_top_k: 10

# Performance Targets
performance:
  p95_latency_ms: 1000
  cache_size: 500
  max_concurrent: 10

# Legal Sources Configuration
sources:
  EUDSA:
    law_id: "EUDSA"
    law_name: "EU Digital Services Act (DSA)"
    jurisdiction: "EU"
    file_path: "legal_texts/EUDSA.txt"
    section_patterns:
      - "Article \\d+(?:\\(\\d+\\))?"
      - "Art\\. \\d+(?:\\(\\d+\\))?"
  
  CA_SB976:
    law_id: "CA_SB976"
    law_name: "California Protecting Our Kids from Social Media Addiction Act"
    jurisdiction: "US-CA"
    file_path: "legal_texts/Cali.txt"
    section_patterns:
      - "Section \\d+(?:\\.\\d+)*"
      - "ยง\\s*\\d+(?:\\.\\d+)*"
  
  FL_HB3:
    law_id: "FL_HB3"
    law_name: "Florida Online Protections for Minors (HB 3)"
    jurisdiction: "US-FL"
    file_path: "legal_texts/Florida_text.txt"
    section_patterns:
      - "ยง\\s*\\d+(?:\\.\\d+)*(?:\\(\\d+\\))*(?:\\([a-z]\\))*"
      - "Section \\d+(?:\\.\\d+)*"
  
  US_2258A:
    law_id: "US_2258A"
    law_name: "18 U.S.C. ยง2258A - Reporting requirements of providers"
    jurisdiction: "US"
    file_path: "legal_texts/NCMEC_reporting.txt"
    section_patterns:
      - "ยง\\s*\\d+[A-Z]*(?:\\(\\w+\\))*"
      - "\\(\\w+\\)"

# Query Expansion Terms
query_expansion:
  age_verification: ["age verification", "age gating", "parental verification", "minor protection"]
  parental_consent: ["parental consent", "guardian approval", "parent permission", "authorized consent"]
  reporting: ["reporting requirements", "notification duties", "disclosure obligations", "compliance reporting"]
  penalties: ["penalties", "violations", "enforcement", "sanctions", "fines"]
  minors: ["minors", "children", "under 18", "under 16", "under 14", "youth"]
